### ISSUE TITLE
Exception: no containers accessible

### ISSUE THREAD

**Issue by gleba** [knrdl/caasa#53]
Hello, why i get this error?
```
caasa-caasa-1  | INFO:     connection open
caasa-caasa-1  | Traceback (most recent call last):
caasa-caasa-1  |   File "/app/ws.py", line 90, in on_receive
caasa-caasa-1  |     response = await _ws_actions[action](websocket.state, **payload)
caasa-caasa-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
caasa-caasa-1  |   File "/app/ws.py", line 38, in inner
caasa-caasa-1  |     return await func(state, **params)
caasa-caasa-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
caasa-caasa-1  |   File "/app/main.py", line 36, in get_system_info
caasa-caasa-1  |     return await docker.get_system_info(state.username)
caasa-caasa-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
caasa-caasa-1  |   File "/app/docker.py", line 59, in get_system_info
caasa-caasa-1  |     raise Exception('no containers accessible')
caasa-caasa-1  | Exception: no containers accessible
```
My compose file:
```
version: '3'
services:
  caasa:
    image: knrdl/caasa
    restart: always
    environment:
      ROLES_caasa_admin_basic: info, state, logs, procs, files, files-read
      ROLES_caasa_admin_full: info, info-annotations, state, logs, term, procs, files, files-read, files-write
      AUTH_API_URL: https://example.org
    ports:
      - "18080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    mem_limit: 150m
    cpu_count: 1
```
